line = "let", assignment | expression;
assignment = identifier, "=", expression;
expression = literal | identifier | "(", operation, ")";
operation = expression, operator, expression;
literal = [sign], integer, [".", integer];
sign = "+" | "-";
operator = "+" | "-" | "*" | "/";
integer = digit, {digit};
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
identifier = letter, {letter};
letter = "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z";
